FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD UserManagement.jar /opt/UserManagement/
EXPOSE 8080
WORKDIR /opt/UserManagement/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "UserManagement.jar"]
